apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-demo-app-config
  namespace: gitops-demo-app
  labels:
    app.kubernetes.io/name: gitops-demo-app
    app.kubernetes.io/part-of: gitops-demo
data:
  PORT: "8080"
  POSTGRES_HOST: postgresql.gitops-demo-services.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_DB: incidents
  RABBITMQ_HOST: rabbitmq.gitops-demo-services.svc.cluster.local
  RABBITMQ_PORT: "5672"
  REDIS_HOST: redis.gitops-demo-services.svc.cluster.local
  REDIS_PORT: "6379"
