apiVersion: v1
data:
  requirements.txt: |+
    Flask==3.0.3
    gunicorn==22.0.0
    pika==1.3.2
    psycopg2-binary==2.9.9
    redis==5.0.4
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: gitops-demo-app
    app.kubernetes.io/part-of: gitops-demo
  name: gitops-demo-app-requirements
  namespace: gitops-demo-app
