apiVersion: v1
kind: Secret
metadata:
  name: gitops-demo-app-secret
  namespace: gitops-demo-app
  labels:
    app.kubernetes.io/name: gitops-demo-app
    app.kubernetes.io/part-of: gitops-demo
type: Opaque
stringData:
  FLASK_SECRET_KEY: gitops-demo-flask-secret
  POSTGRES_USER: gitops_demo
  POSTGRES_PASSWORD: gitops-demo-password
  RABBITMQ_USER: gitops_demo
  RABBITMQ_PASSWORD: gitops-demo-password
  REDIS_PASSWORD: gitops-demo-password

